CREATE DATABASE BluejackLibrary
GO

USE BluejackLibrary
GO

CREATE TABLE MsStaff(
	StaffID CHAR(5) PRIMARY KEY CHECK(StaffID LIKE 'SF[0-9][0-9][0-9]'),
	StaffName VARCHAR(255) NOT NULL,
	StaffGender VARCHAR(50) CHECK(StaffGender IN('Male', 'Female')),
	StaffAddress VARCHAR(255) NOT NULL,
	StaffPhone VARCHAR(50) CHECK (StaffPhone LIKE '+62%'),
	StaffSalary INT NOT NULL
)

CREATE TABLE MsStudent(
	StudentID CHAR(5) PRIMARY KEY CHECK(StudentID LIKE 'ST[0-9][0-9][0-9]'),
	StudentName VARCHAR(255) NOT NULL,
	StudentGender VARCHAR(50) CHECK(StudentGender IN('Male', 'Female')),
	StudentAddress VARCHAR(255) NOT NULL,
	StudentEmail VARCHAR(255) CHECK (StudentEmail LIKE '%@%')
)

CREATE TABLE MsBookCategory(
	BookCategoryID CHAR(5) PRIMARY KEY CHECK(BookCategoryID LIKE 'BC[0-9][0-9][0-9]'),
	BookCategory VARCHAR(50) NOT NULL
)

CREATE TABLE MsBook(
	BookID CHAR(5) PRIMARY KEY CHECK(BookID LIKE 'BK[0-9][0-9][0-9]'),
	BookTitle VARCHAR(255) NOT NULL,
	BookPublishDate DATE CHECK(YEAR(BookPublishDate) > 2011),
	BookStock INT NOT NULL,
	BookRating INT NOT NULL,
	BookCategoryID CHAR(5) FOREIGN KEY REFERENCES MsBookCategory(BookCategoryID) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE MsDonator(
	DonatorID CHAR(5) PRIMARY KEY CHECK(DonatorID LIKE 'DR[0-9][0-9][0-9]'),
	DonatorName VARCHAR(255) NOT NULL,
	DonatorGender VARCHAR(50) NOT NULL,
	DonatorAddress VARCHAR(255) NOT NULL,
	DonatorPhoneNumber VARCHAR(50) NOT NULL
)

CREATE TABLE BorrowHeader(
	BorrowID CHAR(5) PRIMARY KEY CHECK(BorrowID LIKE 'BT[0-9][0-9][0-9]'),
	StudentID CHAR(5) FOREIGN KEY REFERENCES MsStudent(StudentID) ON UPDATE CASCADE ON DELETE CASCADE,
	StaffID CHAR(5) FOREIGN KEY REFERENCES MsStaff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE,
	BorrowDate DATE NOT NULL,
)

CREATE TABLE BorrowDetail(
	BorrowID CHAR(5) FOREIGN KEY REFERENCES BorrowHeader(BorrowID) ON UPDATE CASCADE ON DELETE CASCADE,
	BookID CHAR(5) FOREIGN KEY REFERENCES MsBook(BookID) ON UPDATE CASCADE ON DELETE CASCADE,
	ReturnDate DATE CHECK(ReturnDate > GETDATE()),
	PRIMARY KEY(BorrowID, BookID)
)

CREATE TABLE DonationHeader(
	DonationID CHAR(5) PRIMARY KEY CHECK(DonationID LIKE 'DT[0-9][0-9][0-9]'),
	StaffID CHAR(5) FOREIGN KEY REFERENCES MsStaff(StaffID) ON UPDATE CASCADE ON DELETE CASCADE,
	DonatorID CHAR (5) FOREIGN KEY REFERENCES MsDonator(DonatorID) ON UPDATE CASCADE ON DELETE CASCADE,
	TransactionDate DATE NOT NULL
)

CREATE TABLE DonationDetail(
	DonationID CHAR(5) FOREIGN KEY REFERENCES DonationHeader(DonationID) ON UPDATE CASCADE ON DELETE CASCADE,
	BookID CHAR(5) FOREIGN KEY REFERENCES MsBook(BookID) ON UPDATE CASCADE ON DELETE CASCADE,
	Quantity INT CHECK(Quantity BETWEEN 10 AND 500),
	PRIMARY KEY(DonationID, BookID)
)